[package]
name = "pltx-tui"
description = "Private Life Tracker X TUI"
version = "0.0.1"
edition = "2021"
authors = ["Slekup <opensource@slekup.com>"]
keywords = ["tui", "privacy", "tracker"]
categories = ["tui", "privacy", "tracker"]
documentation = "https://github.com/pltx/tui"
homepage = "https://github.com/pltx/tui"
repository = "https://github.com/pltx/tui"
license = "GPL-3.0"

[[bin]]
name = "pltx"
path = "src/main.rs"

[lib]
name = "pltx"

[profile.release]
panic = "abort"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
home = "0.5.9"
ratatui = { version = "0.26.1", features = ["widget-calendar", "serde"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0.197"
toml = "0.8.12"
tui-scrollview = "0.3.4"
