[package]
name = "pltx-tui"
description = "Private Life Tracker X TUI"
version = "0.0.1"
authors = ["Slekup <opensource@slekup.com>"]
keywords = ["tui", "privacy", "tracker"]
categories = ["tui", "privacy", "tracker"]
documentation = "https://github.com/pltx/tui"
homepage = "https://github.com/pltx/tui"
repository = "https://github.com/pltx/tui"
license = "GPL-3.0"

[features]
default = ["application"]

[dependencies]
