[advisories]
ignore = [
  { id = "RUSTSEC-2024-0320", reason = "Temporary skip until updated by syntect https://github.com/trishume/syntect/issues/537" },
]
yanked = "deny"

[bans]
multiple-versions = "allow"
wildcards = 'allow'

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "GPL-3.0",
  "MIT",
  "MPL-2.0",
  "Unicode-DFS-2016",
]

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
