[bans]
multiple-versions = "deny"
wildcards = 'deny'
skip = [
  { crate = "yaml-rust@0.4.5", reason = "Temporary skip until updated by syntect https://github.com/trishume/syntect/issues/537" },
]

[licences]
version = "2"
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MPL-2.0",
  "BSD-3-Clause",
  "ISC",
]
