[tasks.style-checks]
description = "Style checks"
dependencies = ["check-formatting", "check-typos", "check-docs"]

[tasks.check-formatting]
description = "Lint code formatting"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.format]
description = "Run formatting checks"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-typos]
description = "Run typo checks"
install_crate = { crate_name = "typos-cli", binary = "typos", test_arg = "--version" }
command = "typos"

[tasks.check-docs]
description = "Run doc checks"
command = "cargo"
args = ["rustdoc", "--all-targets", "--all-features"]

[tasks.clippy]
description = "Run cargo clippy"
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--all-features",
  "--tests",
  "--benches",
  "--",
  "-D",
  "warnings",
]

[tasks.check]
description = "Run cargo check"
command = "cargo"
args = ["check", "--all-targets", "--all-features", "--workspace"]

[tasks.test]
description = "Run tests"
install_crate = { crate_name = "cargo-nextest", binary = "cargo-nextest", test_arg = "--help" }
command = "cargo"
args = ["test", "--all-targets", "--all-features", "--workspace"]


[tasks.ci]
description = "Continuous integration tasks"
dependencies = ["style-checks", "clippy", "check", "test"]

[tasks.default]
alias = "ci"

[tasks.yeet]
command = "echo test"
