# Make sure these are the same as .editorconfig
max_width = 100
tab_spaces = 4
hard_tabs = false

format_strings = true
wrap_comments = true
format_code_in_doc_comments = true

use_field_init_shorthand = true

reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
