# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  # Group based on workflow name and PR if it exists, if no PR, let it run so carryforward flags work
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        run: cargo check --verbose

      - name: Format
        run: cargo fmt --all -- --check --verbose

      - name: Clippy
        run: cargo clippy -- -D warnings --verbose

      - name: Test
        run: cargo test --verbose
